name: Build and Deploy Frontend to Firebase

on:
  push:
    branches:
      #- main
      - develop

env:
  PROJECT_ID: connectdatafrontend
  REGION: us-central1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud (Secure Way)
        uses: 'google-github-actions/auth@v2'
        with:          
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Environment based on Git Branch
        run: |
          if [[ $GITHUB_REF_NAME == 'main' ]]; then
            echo "Ambiente de PRODUCCIÓN detectado"
            # La URL de tu bot de PRODUCCIÓN (en el otro proyecto)
            echo "VITE_BOT_API_URL=https://kai-api-prod-537990588927.us-central1.run.app" >> $GITHUB_ENV
            # En Firebase, 'live' es el canal de producción por defecto
            echo "FIREBASE_CHANNEL_ID=live" >> $GITHUB_ENV
          else
            echo "Ambiente de DESARROLLO detectado"
            # La URL de tu bot de DESARROLLO (deberás tener otro servicio de Cloud Run para dev)
            echo "VITE_BOT_API_URL=https://kai-api-dev-537990588927.us-central1.run.app" >> $GITHUB_ENV
            # Crearemos un canal de vista previa en Firebase para el ambiente de desarrollo
            echo "FIREBASE_CHANNEL_ID=develop" >> $GITHUB_ENV
          fi
      
      - name: Install Dependencies and Build Frontend
        working-directory: ./guana-cloud-frontend 
        run: |
          npm install
          # Vite usará automáticamente la variable VITE_BOT_API_URL durante el build
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.GCP_SA_KEY }}'
          projectId: ${{ env.PROJECT_ID }}
          channelId: ${{ env.FIREBASE_CHANNEL_ID }}